services:
  # Main service (backend + frontend)
  - type: web
    name: forkids-app
    env: node
    buildCommand: npm install && cd frontend && npm install && npm run build && cd .. && rm -rf backend/frontend && mkdir -p backend/frontend && xcopy /E /I frontend\build backend\frontend || cp -r frontend/build backend/frontend
    startCommand: cd backend && npm install && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: ZMAIL_USER
        sync: false
      - key: ZMAIL_PASS
        sync: false
      - key: REACT_APP_API_URL
        value: https://forkids-app.onrender.com
      - key: REACT_APP_STRIPE_PUBLISHABLE_KEY
        sync: false 
      - key: ALLOWED_ORIGINS
        sync: false