services:
  # Backend service
  - type: web
    name: forkids-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false

  # Frontend service
  - type: web
    name: forkids-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && serve -s build
    envVars:
      - key: REACT_APP_API_URL
        value: https://forkids-backend.onrender.com
      - key: REACT_APP_STRIPE_PUBLIC_KEY
        sync: false 