const express = require('express');
const router = express.Router();
const path = require('path');
const fs = require('fs');

// This route serves the fallback ZIP files generated by pdfDeliveryService.js
// and webhook.js when a package is too large to email directly (see
// sendPDFWithOptimization / sendCompletePackage / sendPromoPackage).
//
// SECURITY: this folder (backend/public/pdfs) also holds the original paid
// product PDFs. We must NOT allow arbitrary filenames here, or this route
// would let anyone download any product for free without paying.
// Only filenames matching the auto-generated "<name>_<timestamp>.zip"
// pattern used by the zip-generation code are allowed.
const SAFE_GENERATED_ZIP = /^[A-Za-z0-9_]+_\d{10,}\.zip$/;

// Generated links are advertised to customers as valid for 30 days.
const LINK_TTL_MS = 30 * 24 * 60 * 60 * 1000;

router.get('/:filename', (req, res) => {
  const { filename } = req.params;

  if (!SAFE_GENERATED_ZIP.test(filename)) {
    return res.status(400).send('Invalid download link.');
  }

  const filePath = path.join(__dirname, '..', 'public', 'pdfs', filename);
  const resolved = path.resolve(filePath);
  const pdfsDir = path.resolve(path.join(__dirname, '..', 'public', 'pdfs'));

  // Defense in depth against path traversal, even though the regex above
  // already blocks "/" and "..".
  if (!resolved.startsWith(pdfsDir)) {
    return res.status(400).send('Invalid download link.');
  }

  if (!fs.existsSync(resolved)) {
    return res.status(404).send('This download link has expired or is invalid. Please contact contact@corcodusa.ro for help.');
  }

  const stats = fs.statSync(resolved);
  const ageMs = Date.now() - stats.mtimeMs;
  if (ageMs > LINK_TTL_MS) {
    return res.status(410).send('This download link has expired (links are valid for 30 days). Please contact contact@corcodusa.ro for help.');
  }

  res.download(resolved, filename, (err) => {
    if (err && !res.headersSent) {
      res.status(500).send('Error downloading file.');
    }
  });
});

module.exports = router;
